preprocess <- function(cram_file) {
  wd <- dirname(cram_file)
  oldwd <- setwd(wd)
  on.exit(setwd(oldwd))
  script <- system.file("preprocess_single.sh", package = "TrypLik")
  Sys.chmod(script)
  message("Processing... this may take some time")
  system2(script, cram_file)
  sam_file <- file.path(wd, "temp.sam")
  message("result file temp.sam is here: ", sam_file)
  sam_file
}

#' Count Tryptase Alleles in a .sam File
#'
#' @param sam_file path to the temp.sam file generated by the pre-processing
#'
#' @export
count_tryptase <- function(sam_file) {

  sam <- readLines(sam_file)

  a <- length(
    grep(
      r"(CTGCAGC[A]AG[C]GGG[T]ATCGT[C]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[G]CG[A]CC[G])",
      sam
    )
  )
  b <- length(
    grep(
      r"( CTGCAGC[G]AG[T]GGG[C]ATCGT[C]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[A]CG[G]CC[C])",
      sam
    )
  )
  c <- length(
    grep(
      r"(CTGCAGC[G]AG[T]GGG[C]ATCGT[T]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[A]CG[G]CC[C])",
      sam
    )
  )
  d <- length(
    grep(
      r"(CTGCAGC[G]AG[T]GGG[C]ATCGT[T]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[G]CG[A]CC[G])",
      sam
    )
  )

  r1 <- c(
    "CCAGTCCAGGCCCTGCAGCAAGCGGGTATC",
    "C[AG]GGGCCTGGAGGGGTGGGCAAGGGCTGGA",
    "GACGTCAAGGATCTGGCCACCCTCAGGGTG",
    "AGTTCTACATCATCCAGACTGGAGCGGATA",
    "CCGCGTCCACACGGTCATGCTGCCCCCTGC",
    "TGGGGACAGTGGGAGGTGGGGCCAGGGTCT",
    "TTGCCCGGCCCCCTCCTCAGGCTGCACCCT",
    "TGCAGAGCCCCTC[CT]CACCGCCATTTCCCCT",
    "GGAGACGACGTCCGCATCATCCGTGACGAC",
    "CCAGGGCGACTCTGGAGGGCCCCTGGTGTG",
    "TACAGGCGGGCGTGGTCAGCTGGGACGAGG"
  )

  g <- sum(sapply(r1, function(x) length(grep(x, sam))))

  r2 <- c(
    "CCAGGCCAGGCCCTGCAGCGAGTGGGCATC",
    "CGGGGCCTGGAGGGGTGGGGAAGGGCTGGA",
    "GACGTCAAGGATCTGGCCGCCCTCAGGGTG",
    "AGTTCTACACCGCCCAGATCGGAGCGGACA",
    "CCACGTCCACACGGTCACCCTGCCCCCTGC",
    "TGGGGACAGTGGAGGTGGGGCCAGGGTCTT",
    "TTGCCCGGCCCCCTCCTGAGGCTGCACCCT",
    "TGCAGAGCGCCTCCCACCGCCATTTCCTCT",
    "GGAGACGACGTCCGCATCGTCCGTGACGAC",
    "CCAGGGCGACTCCGGAGGGCCCCTGGTGTG",
    "TGCAGGCGGGCGTGGTCAGCTGGGGCGAGG"
  )

  h <- sum(sapply(r2, function(x) length(grep(x, sam))))

  e <- length(grep(r"(CTCAGAGACCTTCCCCCCGGGGATGCCGT)", sam))
  f <- length(grep(r"(CTCAGAGACCTTCCCCCCCGGGGATGCCG)", sam))

  r3 <- c(
    "CCAGGCCAGGCCCTGCAGCAAACGGGCATT",
    "TGGGGCCTGGAGGGGTGGGCAAGGGCTGGA",
    "GACATCAAGGATCTGGCCGCCCTCAGGGTG",
    "AGTTCTACATCATCCAGACCGGGGCGGACA",
    "CCACATCCACAC[GC]GTCACGCTGCCCCCTGC",
    "GGGGACAGCGGGAGGCCGGGCCAGGTGGGC",
    "CCCAGCCGGCCCCAGACCCGGCTCCACGCC",
    "CCCAGTGCACCTGCCGCCGCCATACCCGCT",
    "GGCCACAGCTTTCAAATCGTCCGCGATGAC",
    "CCAGGGTGACTCTGGAGGGCCCCTGGTCTG",
    "TGCAGGCGGGCGTGGTCAGCTGGGAGGAGA"
  )

  i <- sum(sapply(r3, function(x) length(grep(x, sam))))

  c(a, b, c, d, e, f, g, h, i)
}
