#' Run preprocessing script
#'
#' @param cram_file file path of .cram file to be processed
#'
#' @returns produces a temp.sam file
#' @export
#' @examples
#' tryCatch(preprocess("missing_file.cram"), error = function(e) e)
#'
#' \dontrun{
#' preprocess("HG00100.final.cram")
#' }
preprocess <- function(cram_file,
                       output_dir = dirname(cram_file),
                       consensus_dir = system.file(package = "TrypLik"),
                       nthreads = 8
) {
  stopifnot(file.exists(cram_file))
  wd <- output_dir
  bname <- basename(cram_file)
  oldwd <- getwd()
  on.exit(setwd(oldwd))
  script <- system.file("preprocess_single.sh", package = "TrypLik")
  Sys.chmod(script)
  message("Processing... this may take some time")
  ## ensure homebrew paths are respected
  if (!grepl("homebrew", Sys.getenv("PATH"))) {
    Sys.setenv(PATH = paste(Sys.getenv("PATH"), "/opt/homebrew/bin", sep = ":"))
  }
  tc <- tryCatch(
    system2(script, args = c(cram_file, output_dir, consensus_dir, nthreads)),
    error = function(e) e)
  if (tc == 1) stop("Preprocessing bash script encountered an issue, exiting.")
  newfile <- normalizePath(file.path(output_dir, sub(".cram", ".sam", bname, fixed = TRUE)))
  message("result file temp.sam is here: ", newfile)
  invisible(newfile)
}

#' Count Tryptase Alleles in a .sam File
#'
#' @param sam_file path to the temp.sam file generated by the pre-processing
#'
#' @details The first four of values are the numbers of reads mapping uniquely to ⍺,
#' βI, βII or βIII alleles in the specific 83 bp region where
#' all four alleles can be distinguished from each other.
#'
#' The next two are the numbers of reads that map uniquely to β ‘wildtype’
#' (i.e. not frameshifted) and β frameshifted sequences.
#'
#' The final three are the numbers of reads that can be uniquely mapped to
#' ⍺, β, or δ alleles respectively.
#'
#' @returns A vector of counts suitable for input to `TrpLik`. See Details.
#' @export
#' @examples \dontrun{
#' count_tryptase("temp.sam")
#' }
count_tryptase <- function(sam_file) {
  sam <- readLines(sam_file)

  a <- count_a(sam)
  b <- count_b(sam)
  c <- count_c(sam)
  d <- count_d(sam)
  e <- count_e(sam)
  f <- count_f(sam)
  g <- count_g(sam)
  h <- count_h(sam)
  i <- count_i(sam)

  c(a, b, c, d, e, f, g, h, i)
}

count_a <- function(sam) {
  length(
    grep(
      r"(CTGCAGC[A]AG[C]GGG[T]ATCGT[C]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[G]CG[A]CC[G])",
      sam,
      perl = TRUE
    )
  )
}

count_b <- function(sam) {
  length(
    grep(
      r"(CTGCAGC[G]AG[T]GGG[C]ATCGT[C]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[A]CG[G]CC[C])",
      sam,
      perl = TRUE
    )
  )
}

count_c <- function(sam) {
  length(
    grep(
      r"(CTGCAGC[G]AG[T]GGG[C]ATCGT[T]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[A]CG[G]CC[C])",
      sam,
      perl = TRUE
    )
  )
}

count_d <- function(sam) {
  length(
    grep(
      r"(CTGCAGC[G]AG[T]GGG[C]ATCGT[T]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[G]CG[A]CC[G])",
      sam,
      perl = TRUE
    )
  )
}

count_e <- function(sam) {
  length(grep(r"(CTCAGAGACCTTCCCCCCGGGGATGCCGT)", sam, perl = TRUE))
}

count_f <- function(sam) {
  length(grep(r"(CTCAGAGACCTTCCCCCCCGGGGATGCCG)", sam, perl = TRUE))
}

count_g <- function(sam) {
  r1 <- c(
    "CCAGTCCAGGCCCTGCAGCAAGCGGGTATC",
    "C[AG]GGGCCTGGAGGGGTGGGCAAGGGCTGGA",
    "GACGTCAAGGATCTGGCCACCCTCAGGGTG",
    "AGTTCTACATCATCCAGACTGGAGCGGATA",
    "CCGCGTCCACACGGTCATGCTGCCCCCTGC",
    "TGGGGACAGTGGGAGGTGGGGCCAGGGTCT",
    "TTGCCCGGCCCCCTCCTCAGGCTGCACCCT",
    "TGCAGAGCCCCTC[CT]CACCGCCATTTCCCCT",
    "GGAGACGACGTCCGCATCATCCGTGACGAC",
    "CCAGGGCGACTCTGGAGGGCCCCTGGTGTG",
    "TACAGGCGGGCGTGGTCAGCTGGGACGAGG"
  )

  sum(vapply(r1, function(x) find_pat(x, sam), integer(1)))
}

count_h <- function(sam) {
  r2 <- c(
    "CCAGGCCAGGCCCTGCAGCGAGTGGGCATC",
    "CGGGGCCTGGAGGGGTGGGGAAGGGCTGGA",
    "GACGTCAAGGATCTGGCCGCCCTCAGGGTG",
    "AGTTCTACACCGCCCAGATCGGAGCGGACA",
    "CCACGTCCACACGGTCACCCTGCCCCCTGC",
    "TGGGGACAGTGGAGGTGGGGCCAGGGTCTT",
    "TTGCCCGGCCCCCTCCTGAGGCTGCACCCT",
    "TGCAGAGCGCCTCCCACCGCCATTTCCTCT",
    "GGAGACGACGTCCGCATCGTCCGTGACGAC",
    "CCAGGGCGACTCCGGAGGGCCCCTGGTGTG",
    "TGCAGGCGGGCGTGGTCAGCTGGGGCGAGG"
  )

  sum(vapply(r2, function(x) length(grep(x, sam, fixed = TRUE)), integer(1)))
}

count_i <- function(sam) {
  r3 <- c(
    "CCAGGCCAGGCCCTGCAGCAAACGGGCATT",
    "TGGGGCCTGGAGGGGTGGGCAAGGGCTGGA",
    "GACATCAAGGATCTGGCCGCCCTCAGGGTG",
    "AGTTCTACATCATCCAGACCGGGGCGGACA",
    "CCACATCCACAC[GC]GTCACGCTGCCCCCTGC",
    "GGGGACAGCGGGAGGCCGGGCCAGGTGGGC",
    "CCCAGCCGGCCCCAGACCCGGCTCCACGCC",
    "CCCAGTGCACCTGCCGCCGCCATACCCGCT",
    "GGCCACAGCTTTCAAATCGTCCGCGATGAC",
    "CCAGGGTGACTCTGGAGGGCCCCTGGTCTG",
    "TGCAGGCGGGCGTGGTCAGCTGGGAGGAGA"
  )

  sum(vapply(r3, function(x) find_pat(x, sam), integer(1)))
}

find_pat <- function(pat, str) {
  length(
    if (grepl("[", pat, fixed = TRUE)) {
      grep(pat, str, perl = TRUE, fixed = FALSE)
    } else {
      grep(pat, str, fixed = TRUE)
    }
  )
}
