#' Run preprocessing script
#'
#' @param cram_file file path of .cram file to be processed
#'
#' @returns produces a temp.sam file
#' @export
#' @examples
#' tryCatch(preprocess("missing_file.cram"), error = function(e) e)
#'
#' \dontrun{
#' preprocess("HG00100.final.cram")
#' }
preprocess <- function(cram_file) {
    stopifnot(file.exists(cram_file))
    wd <- dirname(cram_file)
    oldwd <- setwd(wd)
    on.exit(setwd(oldwd))
    script <- system.file("preprocess_single.sh", package = "TrypLik")
    Sys.chmod(script)
    message("Processing... this may take some time")
    file.copy(
      system.file("consensus.fa", package = "TrypLik"),
      file.path(wd, "consensus.fa"),
      overwrite = TRUE
    )
    tc <- tryCatch(system2(script, cram_file), error = function(e) e)
    if (tc == 1) stop("Preprocessing bash script encountered an issue, exiting.")
    sam_file <- file.path(wd, "temp.sam")
    message("result file temp.sam is here: ", sam_file)
    sam_file
}

#' Count Tryptase Alleles in a .sam File
#'
#' @param sam_file path to the temp.sam file generated by the pre-processing
#'
#' @details The first four of values are the numbers of reads mapping uniquely to ⍺,
#' βI, βII or βIII alleles in the specific 83 bp region where
#' all four alleles can be distinguished from each other.
#'
#' The next two are the numbers of reads that map uniquely to β ‘wildtype’
#' (i.e. not frameshifted) and β frameshifted sequences.
#'
#' The final three are the numbers of reads that can be uniquely mapped to
#' ⍺, β, or δ alleles respectively.
#'
#' @returns A vector of counts suitable for input to `TrpLik`. See Details.
#' @export
#' @examples \dontrun{
#' count_tryptase("temp.sam")
#' }
count_tryptase <- function(sam_file) {
    sam <- readLines(sam_file)

    a <- count_a(sam)
    b <- count_b(sam)
    c <- count_c(sam)
    d <- count_d(sam)
    e <- count_e(sam)
    f <- count_f(sam)
    g <- count_g(sam)
    h <- count_h(sam)
    i <- count_i(sam)

    c(a, b, c, d, e, f, g, h, i)
}

count_a <- function(sam) {
  length(
    grep(
      r"(CTGCAGC[A]AG[C]GGG[T]ATCGT[C]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[G]CG[A]CC[G])",
      sam
    )
  )
}

count_b <- function(sam) {
  length(
    grep(
      r"(CTGCAGC[G]AG[T]GGG[C]ATCGT[C]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[A]CG[G]CC[C])",
      sam
    )
  )
}

count_c <- function(sam) {
  length(
    grep(
      r"(CTGCAGC[G]AG[T]GGG[C]ATCGT[T]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[A]CG[G]CC[C])",
      sam
    )
  )
}

count_d <- function(sam) {
  length(
    grep(
      r"(CTGCAGC[G]AG[T]GGG[C]ATCGT[T]GGGGGTCAGGAGGCCCCCAGGAGCAAGTGGCCCTGGCAGGTGAGCCTGAGAGTCC[G]CG[A]CC[G])",
      sam
    )
  )
}

count_e <- function(sam) {
  length(grep(r"(CTCAGAGACCTTCCCCCCGGGGATGCCGT)", sam))
}

count_f <- function(sam) {
  length(grep(r"(CTCAGAGACCTTCCCCCCCGGGGATGCCG)", sam))
}

count_g <- function(sam) {
  r1 <- c(
    "CCAGTCCAGGCCCTGCAGCAAGCGGGTATC",
    "C[AG]GGGCCTGGAGGGGTGGGCAAGGGCTGGA",
    "GACGTCAAGGATCTGGCCACCCTCAGGGTG",
    "AGTTCTACATCATCCAGACTGGAGCGGATA",
    "CCGCGTCCACACGGTCATGCTGCCCCCTGC",
    "TGGGGACAGTGGGAGGTGGGGCCAGGGTCT",
    "TTGCCCGGCCCCCTCCTCAGGCTGCACCCT",
    "TGCAGAGCCCCTC[CT]CACCGCCATTTCCCCT",
    "GGAGACGACGTCCGCATCATCCGTGACGAC",
    "CCAGGGCGACTCTGGAGGGCCCCTGGTGTG",
    "TACAGGCGGGCGTGGTCAGCTGGGACGAGG"
  )

  sum(vapply(r1, function(x) length(grep(x, sam)), integer(1)))
}

count_h <- function(sam) {
  r2 <- c(
    "CCAGGCCAGGCCCTGCAGCGAGTGGGCATC",
    "CGGGGCCTGGAGGGGTGGGGAAGGGCTGGA",
    "GACGTCAAGGATCTGGCCGCCCTCAGGGTG",
    "AGTTCTACACCGCCCAGATCGGAGCGGACA",
    "CCACGTCCACACGGTCACCCTGCCCCCTGC",
    "TGGGGACAGTGGAGGTGGGGCCAGGGTCTT",
    "TTGCCCGGCCCCCTCCTGAGGCTGCACCCT",
    "TGCAGAGCGCCTCCCACCGCCATTTCCTCT",
    "GGAGACGACGTCCGCATCGTCCGTGACGAC",
    "CCAGGGCGACTCCGGAGGGCCCCTGGTGTG",
    "TGCAGGCGGGCGTGGTCAGCTGGGGCGAGG"
  )

  sum(vapply(r2, function(x) length(grep(x, sam)), integer(1)))
}

count_i <- function(sam) {
  r3 <- c(
    "CCAGGCCAGGCCCTGCAGCAAACGGGCATT",
    "TGGGGCCTGGAGGGGTGGGCAAGGGCTGGA",
    "GACATCAAGGATCTGGCCGCCCTCAGGGTG",
    "AGTTCTACATCATCCAGACCGGGGCGGACA",
    "CCACATCCACAC[GC]GTCACGCTGCCCCCTGC",
    "GGGGACAGCGGGAGGCCGGGCCAGGTGGGC",
    "CCCAGCCGGCCCCAGACCCGGCTCCACGCC",
    "CCCAGTGCACCTGCCGCCGCCATACCCGCT",
    "GGCCACAGCTTTCAAATCGTCCGCGATGAC",
    "CCAGGGTGACTCTGGAGGGCCCCTGGTCTG",
    "TGCAGGCGGGCGTGGTCAGCTGGGAGGAGA"
  )

  sum(vapply(r3, function(x) length(grep(x, sam)), integer(1)))
}
